#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace ABP_Fabricator { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Hammerhead_01 { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_FloatingLocker_01 { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PCLayer_Vehicle_None { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Tadpole_Scout_Ray { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PCLayer_Vehicle_DiveElevator { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PCore_PostProcess { struct FAnimBlueprintGeneratedConstantData; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace ABP_PCTools_None { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_SN2Player_CameraCorrection { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Tadpole_HAUL { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PCBase_Land { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PCBase_Swim { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PCCarry_Locker { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PCTools_GenericItem { struct FAnimBlueprintGeneratedConstantData; }


namespace ABP_Scanner
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Houndgar_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_ModificationStation
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Biobed
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_PCTools_SharedStates
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Needlershark_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Player_Character
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_AnemoneCrab
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_PCLayer_Vehicle_HAUL
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace oldABP_TwinEels_001
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Processor
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_SN2Player_WaterMotion_Linked
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_SN2PlayerCharacter_Main
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_ElectricGeordie_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_BlightParasite
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Halfmoon_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_TwinEels_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Coralcrab_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_BlightDamagePoint_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Tadpole
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_PCCarry_SharedStates
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_SonicResonator
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Waterslug_01
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Jellyfisher_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_MarrowBreach_01
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_Clamthulu_Nerve_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_RepairTool
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_PCLayer_Vehicle_Tadpole
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Geordie_01
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
