#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALI_Player_Character_Movement

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function ALI_Player_Character_Movement.ALI_Player_Character_Movement_C.The Movement
// 0x0010 (0x0010 - 0x0000)
struct ALI_Player_Character_Movement_C_The_Movement final
{
public:
	struct FPoseLink                              The_Movement_0;                                    // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
DUMPER7_ASSERTS_ALI_Player_Character_Movement_C_The_Movement;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
