#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UWEOceanBiomeRegionActor

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_UWEOceanBiomeRegionActor.BP_UWEOceanBiomeRegionActor_C.ExecuteUbergraph_BP_UWEOceanBiomeRegionActor
// 0x0004 (0x0004 - 0x0000)
struct BP_UWEOceanBiomeRegionActor_C_ExecuteUbergraph_BP_UWEOceanBiomeRegionActor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_UWEOceanBiomeRegionActor_C_ExecuteUbergraph_BP_UWEOceanBiomeRegionActor;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
