#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_UpgradedSonicResonatorHoldCharge_Looping

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function GC_UpgradedSonicResonatorHoldCharge_Looping.GC_UpgradedSonicResonatorHoldCharge_Looping_C.ExecuteUbergraph_GC_UpgradedSonicResonatorHoldCharge_Looping
// 0x0004 (0x0004 - 0x0000)
struct GC_UpgradedSonicResonatorHoldCharge_Looping_C_ExecuteUbergraph_GC_UpgradedSonicResonatorHoldCharge_Looping final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GC_UpgradedSonicResonatorHoldCharge_Looping_C_ExecuteUbergraph_GC_UpgradedSonicResonatorHoldCharge_Looping;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
