#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_GelatinousSkin

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_GelatinousSkin.GE_GelatinousSkin_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_GelatinousSkin_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_GelatinousSkin_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_GelatinousSkin_C")
	}
	static class UGE_GelatinousSkin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_GelatinousSkin_C>();
	}
};
DUMPER7_ASSERTS_UGE_GelatinousSkin_C;

SDK_NAMESPACE_END
