#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Health_Regen

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_Health_Regen.GE_Health_Regen_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_Health_Regen_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Health_Regen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Health_Regen_C")
	}
	static class UGE_Health_Regen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Health_Regen_C>();
	}
};
DUMPER7_ASSERTS_UGE_Health_Regen_C;

SDK_NAMESPACE_END
