#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: L_ClientLobby

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function L_ClientLobby.L_ClientLobby_C.ExecuteUbergraph_L_ClientLobby
// 0x0004 (0x0004 - 0x0000)
struct L_ClientLobby_C_ExecuteUbergraph_L_ClientLobby final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_L_ClientLobby_C_ExecuteUbergraph_L_ClientLobby;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
