#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWEAISpeaker

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UWEAISpeaker.UWEAISpeakerComponent.PlaySound
// 0x0008 (0x0008 - 0x0000)
struct UWEAISpeakerComponent_PlaySound final
{
public:
	class UFMODEvent*                             Event;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UWEAISpeakerComponent_PlaySound;

// Function UWEAISpeaker.UWEAISpeakerComponent.PlaySoundQueued
// 0x0008 (0x0008 - 0x0000)
struct UWEAISpeakerComponent_PlaySoundQueued final
{
public:
	class UFMODEvent*                             Event;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UWEAISpeakerComponent_PlaySoundQueued;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
