#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWEAISpawner

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UWEAISpawner.UWEAISpawner.OnWorldBeingTearDown
// 0x0008 (0x0008 - 0x0000)
struct UWEAISpawner_OnWorldBeingTearDown final
{
public:
	class UWorld*                                 World;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UWEAISpawner_OnWorldBeingTearDown;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
