#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWECuttable

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UWECuttable.UWECuttableData.GetCuttableDataForActor
// 0x0010 (0x0010 - 0x0000)
struct UWECuttableData_GetCuttableDataForActor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UUWECuttableData*                       ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UWECuttableData_GetCuttableDataForActor;

// Function UWECuttable.UWECuttableData.GetCuttableDataForComponent
// 0x0010 (0x0010 - 0x0000)
struct UWECuttableData_GetCuttableDataForComponent final
{
public:
	class UActorComponent*                        ActorComponent;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UUWECuttableData*                       ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UWECuttableData_GetCuttableDataForComponent;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
