#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWEInputActions

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UWEInputActions.UWEConditionalInputDeceleration.DecelerateConditionMet
// 0x0001 (0x0001 - 0x0000)
struct UWEConditionalInputDeceleration_DecelerateConditionMet final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UWEConditionalInputDeceleration_DecelerateConditionMet;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
