#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWENewsfeed

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum UWENewsfeed.FNewsfeedListStatus
// NumValues: 0x0005
enum class EFNewsfeedListStatus : uint8
{
	Uninitialized                            = 0,
	Loading                                  = 1,
	Success                                  = 2,
	Failed                                   = 3,
	FNewsfeedListStatus_MAX                  = 4,
};

SDK_NAMESPACE_END
