#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWESkeletalMeshScalability

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum UWESkeletalMeshScalability.ESkeletalMeshScalabilityGroup
// NumValues: 0x0005
enum class ESkeletalMeshScalabilityGroup : uint8
{
	Misc                                     = 0,
	Resource                                 = 1,
	SmallCreature                            = 2,
	LargeCreature                            = 3,
	ESkeletalMeshScalabilityGroup_MAX        = 4,
};

SDK_NAMESPACE_END
