#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWESteamDeckRuntime

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UWESteamDeckRuntime.UWESteamDeckControllerData.GetSteamDeckControllerName
// 0x0008 (0x0008 - 0x0000)
struct UWESteamDeckControllerData_GetSteamDeckControllerName final
{
public:
	class FName                                   ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UWESteamDeckControllerData_GetSteamDeckControllerName;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
