#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWETemperatureRegions

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum UWETemperatureRegions.ETemperatureContributionType
// NumValues: 0x0003
enum class ETemperatureContributionType : uint8
{
	Additive                                 = 0,
	Set                                      = 1,
	ETemperatureContributionType_MAX         = 2,
};

SDK_NAMESPACE_END
