#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UWEXboxFSE

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UWEXboxFSE.UWEXboxFSEFunctionLibrary.IsDeviceXboxHandheld
// 0x0001 (0x0001 - 0x0000)
struct UWEXboxFSEFunctionLibrary_IsDeviceXboxHandheld final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UWEXboxFSEFunctionLibrary_IsDeviceXboxHandheld;

// Function UWEXboxFSE.UWEXboxFSEFunctionLibrary.IsDeviceXboxHandheldWinGDK
// 0x0001 (0x0001 - 0x0000)
struct UWEXboxFSEFunctionLibrary_IsDeviceXboxHandheldWinGDK final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UWEXboxFSEFunctionLibrary_IsDeviceXboxHandheldWinGDK;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
