#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ConflictingKeybinding

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_ConflictingKeybinding.WBP_ConflictingKeybinding_C.ExecuteUbergraph_WBP_ConflictingKeybinding
// 0x0004 (0x0004 - 0x0000)
struct WBP_ConflictingKeybinding_C_ExecuteUbergraph_WBP_ConflictingKeybinding final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ConflictingKeybinding_C_ExecuteUbergraph_WBP_ConflictingKeybinding;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
