#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CompilingShadersScreen

#include "Basic.hpp"

#include "WBP_CompilingShadersScreen_classes.hpp"
#include "WBP_CompilingShadersScreen_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_CompilingShadersScreen.WBP_CompilingShadersScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CompilingShadersScreen_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CompilingShadersScreen_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CompilingShadersScreen.WBP_CompilingShadersScreen_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CompilingShadersScreen_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CompilingShadersScreen_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CompilingShadersScreen.WBP_CompilingShadersScreen_C.ExecuteUbergraph_WBP_CompilingShadersScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CompilingShadersScreen_C::ExecuteUbergraph_WBP_CompilingShadersScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CompilingShadersScreen_C", "ExecuteUbergraph_WBP_CompilingShadersScreen");

	Params::WBP_CompilingShadersScreen_C_ExecuteUbergraph_WBP_CompilingShadersScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CompilingShadersScreen.WBP_CompilingShadersScreen_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CompilingShadersScreen_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CompilingShadersScreen_C", "PreConstruct");

	Params::WBP_CompilingShadersScreen_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CompilingShadersScreen.WBP_CompilingShadersScreen_C.UpdateCompiling
// (BlueprintCallable, BlueprintEvent)

void UWBP_CompilingShadersScreen_C::UpdateCompiling()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CompilingShadersScreen_C", "UpdateCompiling");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
